<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>05663faf-7fa6-479e-8506-e05fd553114d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Infrastructure/App.fs" />
    <Compile Include="Core/Types.fs" />
    <Compile Include="Core/Utils.fs" />
    <Compile Include="Repositories/HikeRepo.fs" />
    <Compile Include="Views/Components/DatePicker.fs" />
    <Compile Include="Views/Components/TextInput.fs" />
    <Compile Include="Views/Components/Button.fs" />
    <Compile Include="Views/Components/LinkButton.fs" />
    <Compile Include="Views/Components/Table.fs" />
    <Compile Include="Views/Components/Select.fs" />
    <Compile Include="Views/Shared/MasterLayout.fs" />
    <Compile Include="Views/Home/Index.fs" />
    <Compile Include="Views/Plan/ListPlans.fs" />
    <Compile Include="Views/Plan/CreatePlan.fs" />
    <Compile Include="Views/Plan/HikeDetail.fs" />
    <Compile Include="Handlers/Handlers.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Giraffe" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
  </ItemGroup>

</Project>
